.base:
  variables:
    APCI_ALPAKA_ROOT: "$CI_PROJECT_DIR"
    APCI_RUN_CTEST: "ON"
    APCI_EXEC_CPU_SERIAL: "OFF"
    APCI_OMP: "OFF"
    APCI_HWLOC: "ON"
    APCI_HIP : 0
    APCI_CUDA : 0
    APCI_ONEAPI : 0
    APCI_ONEAPI_TARGET: none
    APCI_TBB : "OFF"
    APCI_SANITIZER_ASAN : "OFF"
    APCI_SANITIZER_TSAN : "OFF"
    APCI_SANITIZER_LSAN : "OFF"
    APCI_SANITIZER_UBSAN : "OFF"
    APCI_SIMD : "DEFAULT"
  script:
    - $APCI_ALPAKA_ROOT/script/ci/info.sh
    - $APCI_ALPAKA_ROOT/script/ci/install.sh
    - $APCI_ALPAKA_ROOT/script/ci/configure.sh
    - $APCI_ALPAKA_ROOT/script/ci/build.sh
    - $APCI_ALPAKA_ROOT/script/ci/test.sh
  interruptible: true
  tags:
  - x86_64
  - cpuonly

.cpu:
  extends: .base
  variables:
      APCI_OMP: "ON"

.hip:
  extends: .base
  tags:
    - x86_64
    - rocm

.cuda:
  extends: .base
  image: ubuntu:24.04
  variables:
    APCI_CMAKE: 3.28.3
  tags:
  - x86_64
  - cuda

hipcc-6.4:
  image: docker.io/ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@21
    APCI_CMAKE: 3.28.3
    APCI_HIP : 6.4.2

hipcc-7.0:
  image: ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.31.4
    APCI_HIP : 7.0

hipcc-7.1:
  image: docker.io/ubuntu:24.04
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.28.3
    APCI_HIP : 7.1

hipcc-7.2-rocm-container:
  image: rocm/dev-ubuntu-24.04:7.2
  extends: .hip
  variables:
    APCI_DEVICE_COMPILER : clang@22
    APCI_CMAKE: 3.28.3
    APCI_HIP : 7.2

cuda-12.6-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.6
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.6

cuda-12.8-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.8
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.8

cuda-12.9-gcc-nvidia-container:
  image: nvidia/cuda:12.9.1-devel-ubuntu24.04
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.9
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.9

cuda-13.0-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.0
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.0
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.1-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.1
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.1
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.1-gcc-simd-emulation:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.1
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.1
    APCI_SIMD: EMULATION
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.2-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.2
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.2
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.3-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.3
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.3
  tags:
  - x86_64
  - cuda
  - a100

clang-21-cuda-12.8:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: clang@21
    APCI_CUDA: 12.8
  tags:
  - x86_64
  - cuda
  - a100
